### ISSUE TITLE
Compact representation for vanishing poly $V setminus U$

### ISSUE THREAD

**Issue by antoniofaonio** [HuyHung0/cqplus#1]
https://github.com/HuyHung0/cqplus/blob/267047985be0ff4dc87651a63ee5e586458890c2/src/derive.rs#L174

If we assume H and K are of cardinality $2^h$ and $2^k$ then the vanishing polynomial on $K \setminus U$ is:

$\prod_{i=h...k-1} (X^{2^i} + 1)$

**Comment by HuyHung0** [comment]
In fact, I am thinking of removing the function to compute the vanishing polynomial in

https://github.com/HuyHung0/cqplus/blob/f364314a6ffb841a9a2b70d22040065c8800b45a/src/polynomials.rs#L14-L30

and in

https://github.com/HuyHung0/cqplus/blob/267047985be0ff4dc87651a63ee5e586458890c2/src/derive.rs#L21-L26

The reason is that we only using vanishing polynomial on $K$, $H$, $K\setminus H$ in which $K$ and $H$ are groups. For the vanishing polynomial on $K$, $H$, we use the function `poly_u` = $X^n-1$ in

https://github.com/HuyHung0/cqplus/blob/f364314a6ffb841a9a2b70d22040065c8800b45a/src/polynomials.rs#L83-L89

For the vanishing polynomial on $K\setminus H$, we use the formula $\nu_{K\setminus H} = \nu_K / \nu_H$. This formula should be enough for implementing.
Your formula is correct. Indeed,
$$\nu_{K\setminus H}=\frac{\nu_K}{\nu_H}= \frac{X^{2^k}-1}{X^{2^h}-1}= \frac{\left(X^{2^h} \right)^{2^{k-h}}-1}{X^{2^h}-1} = \prod_{i=0}^{k-h-1}\left( (X^{2^h})^{2^i}+1\right)  = \prod_{i=h}^{k-1} \left(X^{2^i} +1\right)$$

**Comment by HuyHung0** [comment]
The commit https://github.com/HuyHung0/cqplus/commit/a3d48e59ecdbbc85084e4a7829cee7c163f15505 should solve the issue
